/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalmRouteImport } from './routes/calm'
import { Route as IndexRouteImport } from './routes/index'

const CalmRoute = CalmRouteImport.update({
  id: '/calm',
  path: '/calm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calm': typeof CalmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calm': typeof CalmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calm': typeof CalmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calm'
  id: '__root__' | '/' | '/calm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalmRoute: typeof CalmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calm': {
      id: '/calm'
      path: '/calm'
      fullPath: '/calm'
      preLoaderRoute: typeof CalmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalmRoute: CalmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
